name: Trigger auto deployment for miabe-test-nodot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/public/**'
    - '.github/workflows/miabe-test-nodot-AutoDeployTrigger-597f692a-fecb-45c0-a018-c38f6e6ac4eb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MIABETESTNODOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MIABETESTNODOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MIABETESTNODOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/public 
          registryUrl: 
          registryUsername: ${{ secrets.MIABETESTNODOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MIABETESTNODOT_REGISTRY_PASSWORD }}
          containerAppName: miabe-test-nodot
          resourceGroup: frameworksangularbe9a
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


